rsonquery/rsonpath

.gitattributes, .github/workflows/rust.yml
Force all json files in `data` to have LF line endings.
Fixes #15
=> Fix windows line endings

CHANGELOG.md, cliff.toml, crates/rsonpath/src/main.rs
Specifying `--compile` or `-c` will cause rsonpath to compile the query and output its automaton, without running the engine.
This option is mutually exclusive with `--engine` or providing an input path.
Closes #76
=> Compile-only CLI flag

Cargo.lock
Resolves a dev-dependency security vulnerability by removing the `remove-dir-all` dependency entirely.
=> deps: bump tempfile from v3.3.0 to v3.4.0

crates/rsonpath-lib/tests/query_parser_tests.rs
=> test: proptests for parsing array indices queries

crates/rsonpath/src/version.rs
Minor. The Commit SHA part was incorrect, and there seems to be no way to get it when the crate is in registry.
=> fix: remove SHA from --version on crates.io

crates/rsonpath-lib/src/engine/error.rs, crates/rsonpath-lib/src/engine/head_skipping.rs, crates/rsonpath-lib/src/engine/main.rs, crates/rsonpath-lib/src/engine/recursive.rs, crates/rsonpath-lib/src/input.rs, crates/rsonpath-lib/src/input/borrowed.rs, crates/rsonpath-lib/src/input/buffered.rs, crates/rsonpath-lib/src/input/mmap.rs, crates/rsonpath-lib/src/input/owned.rs, crates/rsonpath-lib/src/query/error.rs, crates/rsonpath-lib/src/result.rs, crates/rsonpath-lib/tests/engine_correctness_tests.rs, crates/rsonpath/src/error.rs
The `--result bytes` mode now consistently reports the first byte of the value it matched. This can be used to extract the actual value from the JSON by parsing from the reported byte.
Resolves: #161
=> feat: consistent index result output

Cargo.lock
This removes a tranistive dependency on `atty` with a CVE.
=> dep: bump colored from 2.0.0 to 2.0.4

.vscode/settings.json, README.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/src/engine/main.rs, crates/rsonpath/Cargo.toml, rsonpath.code-workspace
This feature clutters the API more than anything.
If supporting duplicate keys is required in the future, It can be easily added as a config option,
not a compilation one.
=> feat!: remove the unique-members feature

.github/workflows/test-codegen.yml, shell.nix
This patch revises the project's shell.nix to include `rustfmt`.  I am still uncertain as to the root cause of the issue as `rustfmt` should have been installed anyways.  Nonetheless, GHA now passes.
I also took the opportunity to revise up the pinned repository version of the nixpkgs repository to help avoid unrelated issues in the future.
=> Patch Shell.nix to include rustfmt 

Justfile, crates/rsonpath-lib/src/classification.rs, crates/rsonpath-lib/src/classification/memmem/avx2_64.rs, crates/rsonpath-lib/src/classification/quotes.rs, crates/rsonpath-lib/src/classification/quotes/nosimd.rs, crates/rsonpath-lib/src/classification/quotes/shared.rs, crates/rsonpath-lib/src/engine/head_skipping.rs, crates/rsonpath-lib/src/input/borrowed.rs, crates/rsonpath-lib/src/lib.rs, crates/rsonpath-lib/src/query/parser.rs, crates/rsonpath-lib/tests/classifier_correctness_tests.rs, crates/rsonpath-lib/tests/documents/toml/head_skip_long.toml, crates/rsonpath-lib/tests/end_to_end.rs, crates/rsonpath-lib/tests/query_parser_tests.rs, rsonpath.code-workspace
Track down, reproduce, and fix the bug in head skipping caused by one of two scenarios:
- "long" (longer than block size) keys being looked for by head skip;
- very specific scenario where the end of a subtree (the closing character) is exactly at the end of a block, the key being looked for is found in the next block, but whitespace cause the colon to occur in the next-next block (I know).
Resolves: #249
=> Fix: #249 panic during head skipping

.clusterfuzzlite/build.sh, .github/workflows/clusterfuzzlite-batch.yml, .github/workflows/clusterfuzzlite-cron.yml, .github/workflows/clusterfuzzlite-pr.yml, CHANGELOG.md
- Passing the sanitizer didn't work, now the build.sh is fixed.
- Action versions are pinned by hash now.
- Added ability to run batch and cron on-demand, and parameterizing batch with time to fuzz.
=> Tweaks to the fuzzing CI

.github/internal_templates/fuzz_failure.md, CHANGELOG.md, Justfile, crates/rsonpath-lib/src/classification/memmem/nosimd.rs, crates/rsonpath-lib/src/classification/memmem/shared/mask_32.rs, crates/rsonpath-lib/src/classification/memmem/shared/mask_64.rs, crates/rsonpath-lib/src/classification/simd.rs, crates/rsonpath-lib/tests/documents/toml/head_skip_for_curly.toml, crates/rsonpath-lib/tests/documents/toml/head_skip_for_square.toml, crates/rsonpath-lib/tests/end_to_end.rs, crates/rsonpath-test-codegen/src/gen.rs, crates/rsonpath-test/Cargo.toml, crates/rsonpath-test/README.md, fuzz/Cargo.lock
This was detected by fuzzing! Searching for `{` or `[` with descendant would cause a panic
if the input started with the sequence
`{"` or `["`, respectively.
Resolves: #81
=> fix: panic when head-skipping to a single-byte key

.vscode/settings.json, CHANGELOG.md, crates/rsonpath-lib/src/engine.rs, crates/rsonpath-lib/src/engine/empty_query.rs, crates/rsonpath-lib/src/engine/main.rs, crates/rsonpath-lib/src/input.rs, crates/rsonpath-lib/src/input/borrowed.rs, crates/rsonpath-lib/src/input/buffered.rs, crates/rsonpath-lib/src/input/mmap.rs, crates/rsonpath-lib/src/input/owned.rs, crates/rsonpath-lib/src/lib.rs, crates/rsonpath-lib/src/result.rs, crates/rsonpath-lib/tests/documents/toml/atomic_root_empty_string.toml, crates/rsonpath-lib/tests/documents/toml/atomic_root_false.toml, crates/rsonpath-lib/tests/documents/toml/atomic_root_nonempty_string.toml, crates/rsonpath-lib/tests/documents/toml/atomic_root_null.toml, crates/rsonpath-lib/tests/documents/toml/atomic_root_number_float.toml, crates/rsonpath-lib/tests/documents/toml/atomic_root_number_integer.toml, crates/rsonpath-lib/tests/documents/toml/atomic_root_number_scientific_notation.toml, crates/rsonpath-lib/tests/documents/toml/atomic_root_true.toml, crates/rsonpath-lib/tests/end_to_end.rs, crates/rsonpath-lib/tests/input_implementation_tests.rs, crates/rsonpath-test-codegen/src/gen.rs, crates/rsonpath-test-codegen/src/model.rs, rsonpath.code-workspace
The primary goal is to support the empty query on arbitrary JSON documents to behave as one would expect.
```console
$ rq '$' ./empty_file.json -r count
0
```
```console
$ rq '$'
$      {}          
{}
```
```console
$ rq '$'
$ true
true
```
To facilitate that, we move the empty query special case over to a module and specialize all result modes. Most of them are really simple &ndash; asking for count is just asking if the root exists (count of 1) or not (count of 0) and can be done without looking at most of the input. All of those specializations assume valid input JSONs.
As an apropos fix, internal block padding was changed from null bytes to spaces &ndash; null bytes should not appear in a valid JSON at any point, and whitespace are properly neutral to the engine.
Resolves: #160
All …
=> Root-only query handling

.github/workflows/rust.yml
MinGW 13.1.0 broke stuff in the setup-mingw step. Pinning to 12.2.0 is a temporary workaround. See https://github.com/egor-tensin/setup-mingw/issues/14 for details.
=> chore(ci): work around breaking MinGW release

.github/workflows/nix-shell.yml
This PR adds 2 setup steps to the nix-shell workflow.  First, nightly is installed, and then rustfmt.
This allows rustfmt to be run in the workflow in subsequent steps.
This PR is not associated with an existing issue.
- [-] I ran `just verify` locally and it succeeded.
This PR does not change any project-specific code.
=> Add nightly and rustfmt to nix-shell workflow

.github/workflows/test-codegen.yml
Seems our engine tests are not running in CI since some time. Kinda embarassing. Trying to fix the test-codegen flow now...
=> chore(ci): restore test running (hopefully)

.github/workflows/rust.yml, README.md, crates/rsonpath-syntax/src/error.rs, crates/rsonpath/Cargo.toml
The MSRV got unknowingly bumped before, with this CI check we will avoid it in the future.
This also fixes a violation of MSRV in rsonpath-syntax unknowingly introduced in #477 
=> test: add msrv verify as ci check

.gitattributes, crates/rsonpath-lib/src/automaton.rs, crates/rsonpath-lib/src/automaton/minimizer.rs, crates/rsonpath-lib/src/automaton/nfa.rs, crates/rsonpath-lib/src/automaton/state.rs, crates/rsonpath-lib/src/engine/head_skipping.rs, crates/rsonpath-lib/src/engine/main.rs
Improved the access patterns for array index selectors.
First, member and array transitions are now in separate smallvec arrays, so we can always look only at the relevant array transitions.
Second, properties like "has array transition" or "can accept via array transition" are now cached during `minimize` as `StateAttributes`.
Overall on chirop@lille this gives from 7% to 12% thpt increase on most of the `main` benchmark.
See full bench report at the bottom.
Resolves: #138 
Rel: #151 
There is a weird regression on `./data/twitter/twitter.json_user_mentions_indices/rsonpath_mmap_count` which should be investigated as part of #151. However, the change looks reasonably beneficial on all other benches.
``` …
```
=> Improve performance of the index selector

.github/workflows/book.yml, .github/workflows/clusterfuzzlite-cron.yml, .github/workflows/rust.yml, crates/rsonpath-lib/src/automaton.rs, crates/rsonpath-lib/src/automaton/minimizer.rs, crates/rsonpath-test/documents/toml/lists.toml
Fixed a bug where the compiler would erronously mark states with a single slice transition as unitary, even though such transitions could match more than one index.
=> fix: child slice selectors only selecting first matching index

crates/rsonpath-lib/src/result/approx_span.rs
New clippy lint introduced in nightly (`clippy::too-long-first-doc-paragraph`) was being triggered on the top module comment for `result::approx_span`.
=> split long doc comment in `approx_span`

Cargo.lock, crates/rsonpath-syntax/src/parser.rs
New nightly lint `elided_named_lifetimes` got triggered on a function in `rsonpath-syntax`. In this case the named lifetime is redundant itself, so the fix is to just turn it into an anonymous one.
=> fix nightly lint failing the CI pipelines

crates/rsonpath-syntax/src/builder.rs, crates/rsonpath-syntax/src/lib.rs, crates/rsonpath-syntax/src/parser.rs
According to the spec the start of a slice when not explicitly specified depends on the sign of the step. The current implementation always used FromStart(0), which is correct for forward steps, but for backward steps it's supposed to be starting from the end - FromEnd(1).
This affects only `rsonpath-syntax`.
Resolves: #546 
=> fix default slice start in parser

.github/workflows/benchmarks.yml, .github/workflows/book.yml, .github/workflows/clusterfuzzlite-batch.yml, .github/workflows/dependency-review.yml, .github/workflows/nix-shell.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/scorecards.yml, .github/workflows/test-codegen.yml
chore(ci): bump auguwu/clippy-action from a1f4eaac010d8f420818674bdd5eb9937e7efe26 to 8dc2ea8f7d624bf06a22145cc62fd8bc7d6b0a3e
chore(ci): bump actions/checkout from 3 to 4
chore(ci): bump actions/cache from 3 to 4
chore(ci): bump actions/setup-java from 3.6.0 to 4.5.0
=> rollup actions bumps from dependabot into a single commit

.github/workflows/benchmarks.yml, .github/workflows/book.yml, .github/workflows/closed-issue.yml, .github/workflows/clusterfuzzlite-batch.yml, .github/workflows/clusterfuzzlite-cron.yml, .github/workflows/clusterfuzzlite-pr.yml, .github/workflows/dependency-review.yml, .github/workflows/new-issue.yml, .github/workflows/nix-shell.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/scorecards.yml, .github/workflows/test-codegen.yml, .github/workflows/triaged-issue.yml
This is a manual version of #608 which is borked
Bumps the ci-deps group with 6 updates in the / directory:
| Package | From | To |
| --- | --- | --- |
| [actions/cache](https://github.com/actions/cache) | `4.1.2` | `4.2.0` | | [step-security/harden-runner](https://github.com/step-security/harden-runner) | `2.10.1` | `2.10.2` | | [actions/dependency-review-action](https://github.com/actions/dependency-review-action) | `4.4.0` | `4.5.0` | | [softprops/action-gh-release](https://github.com/softprops/action-gh-release) | `2.0.9` | `2.2.0` | | [EmbarkStudios/cargo-deny-action](https://github.com/embarkstudios/cargo-deny-action) | `2.0.1` | `2.0.4` | | [github/codeql-action](https://github.com/github/codeql-action) | `3.27.0` | `3.27.9` |
Updates `actions/cache` from 4.1.2 to 4.2.0
- [Release …
=> chore(ci): bump the ci-deps group across 1 directory with 6 updates

crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/src/automaton.rs, crates/rsonpath-lib/src/automaton/minimizer.rs, crates/rsonpath-lib/src/automaton/nfa.rs, crates/rsonpath-lib/src/engine/head_skipping.rs, crates/rsonpath-lib/src/engine/main.rs
Improve the change from #618 to instead use `Arc` references and make `MainEngine` both `Sync` and `Send` again. 
Resolves: #620
=> Add feature 'multithread' to use Rsonpath in multithread context

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, Justfile, README.md, book/src/user/installation.md, crates/rsonpath-benchmarks/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, fuzz/Cargo.lock
=> release v0.9.3

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/release.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, Justfile, README.md, book/src/user/installation.md, crates/rsonpath-benchmarks/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-syntax-proptest/Cargo.toml, crates/rsonpath-syntax/CHANGELOG.md, crates/rsonpath-syntax/Cargo.toml, crates/rsonpath-syntax/README.md, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, fuzz/Cargo.lock
=> release v0.9.4

.github/workflows/release.yml, .github/workflows/rust.yml
GitHub added support for linux ARM runners a few months ago. These are most likely more efficient than our self-hosted one, so let's try to use them.
=> ci: use github hosted ARM runners

crates/rsonpath-benchmarks/Cargo.toml, crates/rsonpath-benchmarks/src/framework.rs, crates/rsonpath-benchmarks/src/implementations/jsonpath_rust.rs, crates/rsonpath-benchmarks/src/main.rs, crates/rsonpath-lib/src/classification/structural/nosimd.rs, crates/rsonpath-lib/src/classification/structural/shared.rs, crates/rsonpath-lib/src/engine.rs, crates/rsonpath-lib/src/engine/main.rs, crates/rsonpath-test/Cargo.toml
Tail skipping was not triggered when the item matching the unitary transition was an atomic value inside a list. For example, selecting `$[0]` from a long list of integers would never skip, massively degrading performance.
Skipping was added to `handle_comma` in the same vein as it was in `handle_colon` to enable this.
Resolves: #751
=> fix: skipping inside arrays on comma-atomic
