rsonquery/rsonpath

Cargo.lock, rsonpath/Cargo.toml, rsonpath/src/main.rs, rsonpath/src/query.rs, rsonpath/src/query/errors.rs, rsonpath/src/query/parser.rs
=> deps: removed usage of eyre from library code

Cargo.lock, README.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/src/classify/avx2.rs, crates/rsonpath-lib/src/engine.rs, crates/rsonpath-lib/src/quotes.rs, crates/rsonpath-lib/src/quotes/avx2.rs, crates/rsonpath-lib/src/quotes/nosimd.rs
Closes #37 
Also updated README for current deps.
=> deps: removed `len_trait` dependency

.github/workflows/release.yml, .github/workflows/rust.yml, CHANGELOG.md, cliff.toml, crates/rsonpath-benchmarks/Cargo.toml, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/src/classify.rs, crates/rsonpath-lib/src/classify/nosimd.rs, crates/rsonpath-lib/src/depth/nosimd.rs, crates/rsonpath-lib/src/engine.rs, crates/rsonpath-lib/src/lib.rs, crates/rsonpath-lib/src/quotes.rs, crates/rsonpath-lib/src/quotes/nosimd.rs, crates/rsonpath-lib/tests/engine_correctness_test.rs, crates/rsonpath/Cargo.toml, crates/rsonpath/src/main.rs
=> ci: update workflows and create Release workflow

.github/workflows/rust.yml, Makefile, cliff.toml, crates/rsonpath-benchmarks/build.rs, crates/rsonpath-benchmarks/src/rsonpath.rs, crates/rsonpath-lib/src/lib.rs, crates/rsonpath-lib/src/query.rs, crates/rsonpath-lib/src/query/errors.rs, crates/rsonpath-lib/src/query/parser.rs
=> lib: `query` module is now panic-free

.github/workflows/release.yml, crates/rsonpath-lib/src/classify/avx2.rs, crates/rsonpath-lib/src/depth/avx2.rs, crates/rsonpath-lib/src/quotes/avx2.rs
=> Fix install

img/main-plot.svg
=> docs: update main plot in README

.github/workflows/release.yml, .github/workflows/rust.yml, crates/rsonpath-lib/Cargo.toml
=> Fix CI pipelines

.github/workflows/nix-shell.yml, shell.nix
This change includes support for nix-based environments in the project via a nix shell file.
There is not currently an issue for this item.
I am not sure if the submodules are updated correctly.
Thanks!
=> Shell.nix created

Justfile, crates/rsonpath-lib/src/error.rs, crates/rsonpath-lib/src/query.rs, crates/rsonpath-lib/src/query/automaton/minimizer.rs, crates/rsonpath-lib/src/query/automaton/nfa.rs, crates/rsonpath-lib/src/query/builder.rs, crates/rsonpath-lib/src/query/error.rs, crates/rsonpath-lib/src/query/parser.rs, crates/rsonpath-lib/tests/query_parser_tests.rs, crates/rsonpath/src/lib.rs
This PR implements the non-negative index selector.
Resolves: #60
=> 60 index selector non negative

.vscode/settings.json, crates/rsonpath-lib/src/query/automaton/minimizer.rs, crates/rsonpath-lib/src/query/automaton/nfa.rs, crates/rsonpath-lib/src/query/automaton/small_set.rs, crates/rsonpath-lib/tests/query_parser_tests.rs, rsonpath.code-workspace
Added more cases for compiling the DFA and minimizing for queries with wildcards.
Test improvements, no behavioral changes.
=> tests: more tests for wildcard compilation

.github/workflows/release.yml
Introducing provenance generation and signing to binaries produced on release.
See: https://slsa.dev/spec/v1.0/about
=> Add SLSA3 provenance to the release pipeline.

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, Justfile, README.md, book/src/user/installation.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, crates/rsonpath/Cargo.toml
=> release v0.7.1

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, README.md, book/src/user/installation.md, book/src/user/installation/manual.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, crates/rsonpath/Cargo.toml, fuzz/Cargo.lock
=> release v0.8.1

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, Justfile, README.md, book/src/user/installation.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-lib/src/input.rs, crates/rsonpath-lib/src/input/buffered.rs, crates/rsonpath-lib/src/input/owned.rs, crates/rsonpath-lib/src/lib.rs, crates/rsonpath-lib/src/result/nodes.rs, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, crates/rsonpath/Cargo.toml, deny.toml, fuzz/Cargo.lock
=> release v0.8.2

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, Justfile, README.md, book/src/user/installation.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-lib/src/lib.rs, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, crates/rsonpath/Cargo.toml, fuzz/Cargo.lock, fuzz/Cargo.toml
=> release v0.8.4

.clusterfuzzlite/Dockerfile, .github/dependabot.yml, .github/workflows/book.yml, .github/workflows/closed-issue.yml, .github/workflows/clusterfuzzlite-batch.yml, .github/workflows/clusterfuzzlite-cron.yml, .github/workflows/clusterfuzzlite-pr.yml, .github/workflows/dependency-review.yml, .github/workflows/nix-shell.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/test-codegen.yml
Make step security runner rules block egress by default.
Audit was running long enough to move to an allowlist.
=> restrict step security egress rules

.github/workflows/release.yml, .github/workflows/rust.yml
Adding a self-hosted ARM64 runner for CI.
=> use self-hosted runner for ARM

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, README.md, book/src/user/installation.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-syntax/CHANGELOG.md, crates/rsonpath-syntax/README.md, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, crates/rsonpath/Cargo.toml, deny.toml, fuzz/Cargo.lock
=> release v0.8.5

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, README.md, book/src/user/installation.md, book/src/user/installation/manual.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-syntax/CHANGELOG.md, crates/rsonpath-syntax/Cargo.toml, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, crates/rsonpath/Cargo.toml, fuzz/Cargo.lock
=> release v0.9.0

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Cargo.lock, Justfile, README.md, book/src/user/installation.md, book/src/user/installation/manual.md, crates/rsonpath-lib/Cargo.toml, crates/rsonpath-lib/README.md, crates/rsonpath-test-codegen/Cargo.lock, crates/rsonpath-test-codegen/Cargo.toml, crates/rsonpath-test/Cargo.toml, crates/rsonpath/Cargo.toml, fuzz/Cargo.lock
=> release v0.9.1

crates/rsonpath-lib/src/engine/main.rs
No functional changes. I did a pass over the main engine, added comments and refactored a few things to make it clearer.
Resolves: #130 
=> chore(doc): added comments to the main engine code

Cargo.lock, crates/rsonpath-lib/src/automaton.rs, crates/rsonpath-lib/src/automaton/array_transition_set.rs, crates/rsonpath-lib/src/automaton/minimizer.rs, crates/rsonpath-lib/src/automaton/small_set.rs, crates/rsonpath-lib/src/classification.rs, crates/rsonpath-lib/src/classification/memmem.rs, crates/rsonpath-lib/src/classification/quotes/avx2_32.rs, crates/rsonpath-lib/src/classification/quotes/avx2_64.rs, crates/rsonpath-lib/src/classification/quotes/sse2_32.rs, crates/rsonpath-lib/src/classification/quotes/sse2_64.rs, crates/rsonpath-lib/src/input/borrowed.rs, crates/rsonpath-lib/src/input/buffered.rs, crates/rsonpath-lib/src/input/mmap.rs, crates/rsonpath-lib/src/input/owned.rs, crates/rsonpath-syntax/src/lib.rs, deny.toml
I left the repo unmaintained for some time and dependabot updates started failing due to new lints in nightly versions and some dependency incompatibilities. This PR should restore everything to a stable state.
=> Fix nightly CIs

crates/rsonpath-lib/src/automaton.rs, crates/rsonpath-lib/src/automaton/nfa.rs, crates/rsonpath-lib/src/classification/memmem/nosimd.rs, crates/rsonpath-lib/src/engine/main.rs, crates/rsonpath-lib/src/input/borrowed.rs, crates/rsonpath-lib/src/input/buffered.rs, crates/rsonpath-lib/src/input/padding.rs, crates/rsonpath-lib/src/result/approx_span.rs, crates/rsonpath-lib/src/result/index.rs, crates/rsonpath-lib/src/result/nodes.rs, crates/rsonpath-lib/tests/input_implementation_tests.rs, crates/rsonpath/src/runner.rs
_Please remove this section before posting the PR._
_You need to tick all the items outlined in the **checklist** or the PR will likely be rejected.
Any exceptions need to be justified. If you fail to meet these criteria, consider a draft PR._
_PRs should have an associated issue that was triaged and
accepted, i.e. assigned the <span style="color: #FF4400">acceptance: go ahead</span>
label. Only cosmetic PRs are exempt from this rule, i.e._
- _Minor dependency bumps._
- _Minor documentation tweaks._
- _Minor refactorings._
_In those cases, remove the **Issue** section and replace it with a justification._
The [`needless_lifetimes`](https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes) lint became active and now fires a bunch of times in our repo. This just fixes …
=> fix nightly clippy
